website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'PASSWORD' #secure cookies/session data related to website

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix ='/')
    app.register_blueprint(auth, url_prefix ='/')


    return app

website/auth.py
from flask import Blueprint, render_template

auth = Blueprint('auth', __name__)



@auth.route('/login')
def login():
    return "<p>Login</p>"

@auth.route('/logout')
def logout():
    return "<p>logout</p>"

@auth.route('/sign-up')
def sign_up():
    return "<p>Sign Up</p>"

website/views.py
from flask import Blueprint, render_template

views = Blueprint('views', __name__) #define file as a blueprint file

@views.route('/')
def home():
    return render_template("home.html")
    #return "<p>Home<p>"

@views.route('/project_1')
def project_1():
    return render_template("project_1.html")
    #return "<p>Home<p>"

@views.route('/project_2')
def project_2():
    return render_template("project_2.html")
    #return "<p>Home<p>"

@views.route('/project_3')
def project_3():
    return render_template("project_3.html")
    #return "<p>Home<p>"

@views.route('/project_4')
def project_4():
    return render_template("project_4.html")
    #return "<p>Home<p>"

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HappyHaikal</title>
  <!-- Bootstrap CSS for responsive layout and styling -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font links for custom typography -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="static/home/asset_13.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,800;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='style_home.css') }}">
</head>
<body>
  <!-- Hamburger Menu Button -->
  <button class="hamburger">☰</button>

  <!-- Top Navbar -->
  <div class="side-navbar" id="sideNavbar">
    <div class="logo-container">
      <a href="{{ url_for('views.home') }}">
        <img src="static/home/asset_14.png" alt="Logo">
      </a>
    </div>  
    <div class="nav-links">
      <a href="#projects">PROJECTS</a>
      <a href="#cv">CV</a>
      <a href="#about">ABOUT</a>
      <a href="#contact">CONTACT</a>
    </div>
  </div>

  <!-- Main Content -->
  <div class="content">
    <!-- Hero Section with Typing Animation -->
    <header class="custom-hero py-5">
      <div class="container d-flex flex-column align-items-center">
        <h1 class="typing-container">
          <span id="typing-text"></span>
          <span class="blinking-cursor"></span>
        </h1>
        <div class="inline-container">
          <p class="poppins hero-text" style="max-width:600px;">
            I am currently an undergraduate student at the Singapore University of Technology and Design (SUTD).
            I love solving problems through design, engineering, and technology. My drive comes from a passion for mechanical design 
            and engineering, as well as a strong desire to make a meaningful impact on society.
            I have experience with CAD, coding, 3D printing, and design. Plus, I bring lots of happy energy :)
          </p>
          <img src="static/home/picture_2.png" alt="Hero Image" class="hero-image">
        </div>
        <div class="button-container">
              <a href="#projects"
              class="btn btn-light btn-lg"
              style="background-color: #dfe4e6; color: #050505;">
            Learn More
              </a>
        </div>
      </div>
    </header>

  <!-- Projects Section -->
  <section id="projects">
    <div class="container">
      <h2>My Projects</h2>
      <div class="project-row">
        
        <!-- Project Card 1 -->
        <div class="project-card">
          <div class="image-wrapper">
            <img src="static/home/project_1.gif" alt="Background animation" />
          </div>
          <div class="card-body">
            <h5 class="card-title">Blaster/Airlab</h5>
        
            <div class="card-tags">
              <span class="tag">CAD</span>
              <span class="tag">Arduino</span>              
              <span class="tag">Design</span>
            </div>
        
            <a href="{{ url_for('views.project_1') }}#top" class="btn-primary">View Project</a>
          </div>
        </div>
  
        <!-- Project Card 2 -->
        <div class="project-card">
          <div class="image-wrapper">
            <img src="static/home/project_2.gif" alt="Background animation" />
          </div>
          <div class="card-body">
            <h5 class="card-title">Mechanical Toy Car</h5>

            <div class="card-tags">
              <span class="tag">CAD</span>
              <span class="tag">Mechanical</span>
            </div>

            <a href="{{ url_for('views.project_2') }}#top" class="btn-primary">View Project</a>
          </div>
        </div>

        <!-- Project Card 3 -->
        <div class="project-card">
          <div class="image-wrapper">
            <img src="static/home/project_3.gif" alt="Background animation" />
          </div>
          <div class="card-body">
            <h5 class="card-title">SkyWatchHub</h5>

            <div class="card-tags">
              <span class="tag">CAD</span>
              <span class="tag">Design thinking</span>
            </div>

            <a href="{{ url_for('views.project_3') }}#top" class="btn-primary">View Project</a>
          </div>
        </div>

        <!-- Project Card 4 -->
        <div class="project-card">
          <div class="image-wrapper">
            <img src="static/home/project_4.gif" alt="Background animation" />
          </div>
          <div class="card-body">
            <h5 class="card-title">Omni-Node</h5>

            <div class="card-tags">
              <span class="tag">Electronics</span>
              <span class="tag">Circuits</span>
            </div>

            <a href="{{ url_for('views.project_4') }}#top" class="btn-primary">View Project</a>
          </div>
        </div>
  
  
        <!-- Add more cards as needed -->
  
      </div>
    </div>
  </section>


    <!-- CV Section -->
    <section id="cv" class="py-5">
      <div class="container text-center">
        <h2>Curriculum Vitae</h2>
        <div class="row mt-4">
          <div class="col-md-6">
            <h5>Education</h5>
            <h6>2023 – Present</h6>
            <ul>
              <li>
                Undergraduate, Singapore University of Technology and Design (SUTD) – Major in 
                Engineering Product Development (Mechanical Engineering)
              </li>
            </ul>
        
            <h6>2018 – 2021</h6>
            <ul>
              <li>
                Diploma with Merit in Aerospace Engineering (graduating with 4.0/4.0 gpa) 
                Temasek Polytechnic, Singapore
              </li>
            </ul>

            <h5>Certifications</h5>
            <ul>
              <li>Certified SolidWorks Associate (CSWA) – Dassault Systèmes (2024)</li>
            </ul>

          </div>


          <div class="col-md-6">
            <h5>Skills</h5>
            <ul>
              <li>CAD & FEA: SolidWorks, Fusion360, Creo</li>
              <li>Programming: Python, C++</li>
              <li>Web Development: HTML, CSS, Flask </li>
              <li>3D Printing, Circuit Design</li>
              <li>Machine learning: Scikit-learn </li>
            </ul>

            <h5>Academic Awards</h5>
            <ul>
              <li>SUTD Global Distinguished Scholarship</li>
              <li>SUTD-Prima Scholarship</li>
              <li>ST Engineering Aerospace Engineering Course Silver Medal</li>
              <li>Junior Director's List Award (Temasek Polytechnic)</li>
              <li>Freshman Director's List Award (Temasek Polytechnic)</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="mt-4  text-center">
        <a href="static/home/resume_haikal.pdf" download class="btn btn-primary">Download Resume (PDF)</a>
      </div>
    </div> <!-- end of container -->
    </section>

   <!-- About Section with Timeline -->
<section id="about" class="py-5">
  <div class="container text-center">
    <h2>About Me</h2>
    <p class="mt-3">Here’s a visual journey of my life and key moments that shaped who I am today.</p>

    <section class="timeline">
      <!-- Timeline Event 2 -->
      <div class="timeline-item">
        <div class="timeline-content">
          <h4>2016</h4>
          <p>During secondary school, Design and Technology was my favourite subject. It
              was where I could exercise my passions - drawing and designing. The workshop
              was always a blast. Being able to use the lathe, band saw and metal bender opened my eyes
              to what I could make. I would also say that alot of my cheerful, outspoken and bubbly
              personality comes from the friends and experiences I made here. 
              Being a leader in the student executive comittee, being an emcee for school events 
              and learning from my teachers had taught me many life long values.
          </p>
        </div>
        <div class="timeline-node"></div>
        <div class="timeline-image-wrapper">
          <img src="static/home/node_1.gif" alt="Slide 2" class="timeline-image" />
        </div>
      </div>

      <!-- Timeline Event 3 -->
      <div class="timeline-item">
        <div class="timeline-content">
          <h4>2020</h4>
          <p>
              I chose to pursue Aerospace Engineering post secondary school as I 
              had aspirations being an LAE (licensed aircraft engineer). However, I 
              realised that the MRO (maintanence, repair and overhaul) industry was not 
              for me. Though, I found the physics(fluid dynamics, kinematics) fascinating.
              CAD (computer aid design), C++ programming, Arduino and 
              electronics classes were also favourites.
          </p>
        </div>
        <div class="timeline-node"></div>
        <div class="timeline-image-wrapper">
          <img src="static/home/node_2.gif" alt="Slide 2" class="timeline-image" />
        </div>
      </div>

      <!-- Timeline Event 4 -->
      <div class="timeline-item">
        <div class="timeline-content">
          <h4>2023</h4>
          <p>
             My love for designing and engineering ultimately led me to choose to join SUTD (Singapore University
             of Technology and Design). Being able to design and engineer solutions to help people for
             a living sounded less like a job and more of a natural calling. Hopefully, as I work hard 
             to master my skills in mechanical engineering and design, I can make a 
             difference to society.
          </p>
        </div>
        <div class="timeline-node"></div>
        <div class="timeline-image-wrapper">
          <img src="static/home/node_3.gif" alt="Slide 2" class="timeline-image" />
        </div>
      </div>

      <!-- Timeline Event 5 -->
      <div class="timeline-item">
        <div class="timeline-content">
          <h4>Present me</h4>
          <p>
            I'm currently exploring advanced projects in robotics and mechanics 
            and IoT technologies, blending design thinking with 
            engineering solutions. I'm eager to 
            take on real-world challenges and contribute meaningfully to 
            both my community and the industry.
          </p>
        </div>
        <div class="timeline-node"></div>
        <div class="timeline-image-wrapper">
          <img src="static/home/node_4.gif" alt="Slide 2" class="timeline-image" />
        </div>
      </div>
    </section>
  </div>
</section>

    </div>
  </section>

  <!-- Contact Section -->
<section id="contact" class="contact-section">
  <div class="contact-container">
    <h2>Contact Me</h2>
    <div class="social-icons">
      <a href="mailto:muhamedhaikal6@gmail.com" class="icon-btn" aria-label="Email">
        <i class="fas fa-envelope fa-3x"></i>
      </a>
      <a href="https://www.linkedin.com/in/muhamad-haikal-bin-mohamed" target="_blank" class="icon-btn2" aria-label="LinkedIn">
        <i class="fab fa-linkedin fa-3x"></i>
      </a>
    </div>
  </div>
</section>

    <footer>
      <p>Built and designed by Haikal :) using Flask, HTML, CSS, and JavaScript.</p>
      <p>&copy; HappyHaikal</p>
    </footer>
  </div>

  <!-- Bootstrap JS and Dependencies -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Typing Animation Script -->
  <script>
    const typingText = document.getElementById('typing-text');
    const text = "Hello there, I am Haikal!";
    let index = 0;
    function type() {
      if (index < text.length) {
        typingText.innerHTML += text.charAt(index);
        index++;
        setTimeout(type, 150);
      }
    }
    type();
  </script>
  <script>
    // Hamburger Menu Toggle
    const hamburger = document.querySelector('.hamburger');
    const sideNavbar = document.getElementById('sideNavbar');
    hamburger.addEventListener('click', () => {
      sideNavbar.classList.toggle('open');
    });
  </script>
  <script>
    document.querySelectorAll('.nav-links a').forEach(link => {
      link.addEventListener('click', () => {
        sideNavbar.classList.remove('open');
      });
    });
  </script>
</body>
</html>

website/templates/project_2.html
{% extends 'base_project.html' %}

{% block intro %}
<section id="about">
    <div class="container">
        <h2>Mechanical-Powered Toy Car</h2>
        <p>As part of an undergraduate project at the Singapore University of Technology and 
            Design, students were challenged to design a car <strong>powered solely by mechanical energy</strong> 
            to transport a 400g payload through an obstacle course. Additional marks were awarded 
            to teams whose cars successfully completed the course.
        </p>
        
        <div class="row">
            <div class="column">
                <h5>My Role</h5>
                <p>In charge of CAD, design of mechanism</p>
            </div>
            <div class="column">
                <h5>My Contribution</h5>
                <p>CAD, Design of final car, Prototyping, Testing</p>
            </div>
        </div>
        
        <div class="row">
            <div class="column">
                <h5>About the Team</h5>
                <p>Team of 5 </p>
            </div>
            <div class="column">
                <h5>Year</h5>
                <p>2023</p>
            </div>
        </div>
        
        <div class="row">
            <div class="column">
                <h5>Platform</h5>
                <p>SolidWork, 3D printing</p>
            </div>
            <div class="column">
                <h5>Time Frame</h5>
                <p>1 semester (14 weeks)</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}


{% block gallery %}
<!-- Gallery -->
<div class="photo-collage">
    <div class="image-container">
        <div class="image-wrapper">
            <img src="static/project_2/gear_spinning.gif" alt="Slide 2" class="fullscreen-img" />
            <button class="fullscreen-btn" onclick="openFullscreen(this)">⛶</button>
        </div>             
        <img src="static/project_2/testing_2.gif" alt="Looping animation 2" />
    </div>

    <div class="image-container">
        <img src="static/project_2/course_2.gif" alt="Looping animation 2" />
        <div class="image-wrapper">
            <img src="static/project_2/car_5.jpg" alt="Slide 2" class="fullscreen-img" />
            <button class="fullscreen-btn" onclick="openFullscreen(this)">⛶</button>
        </div>  
    </div>

    <div class="image-container">
        <img src="static/project_2/testing_car_2.gif" alt="Looping animation 2" />
        <div class="image-wrapper">
            <img src="static/project_2/car_4.jpg" alt="Slide 2" class="fullscreen-img" />
            <button class="fullscreen-btn" onclick="openFullscreen(this)">⛶</button>
        </div>  
    </div>
</div>
<!-- Gallery -->
{% endblock %}

{% block section %}
<!-- CAD Section-->
<section id="cad"> 
    <div class="container">
        <h2>Project Rules</h2>
        <p class="mt-3"> <strong>Objective</strong>: Design and build a mechanical energy powered toy car that can carry a load travelling across an
            obstacle course, using the principles of classical mechanics. <strong>The rules 
            are as follows:</strong>
        </p>

        <ol class="car_rule_list">
        <li> The toy car must be able to carry a <strong>minimum 
            load of 200 g (up to maximum of 400 g)</strong> in an open top compartment 
            on board securely across an obstacle course within <strong>time 
            limit of 10 sec</strong>. The loads come in 
            pieces of 100 g each, with dimension of 3.2 cm x 3.2 cm x 3.5 cm
        </li>
        <li> 
            The toy car must be <strong>no larger than 25 cm in length and 12 cm in width</strong> (no limit to height)
        </li>
        <li> 
            The toy car must possess an <strong>on‐board mechanical energy source </strong>(no electrical energy or
            chemical energy allowed)</li>
        <li> 
            All individual components in the toy car must be <strong>customed made</strong>(e.g. using 3D printing or
            laser cutting of wooded or acrylic board) or salvaged as recycle parts
        </li>
        </ol>

        <div class="content-wrapper">
            <div class="education">
                <h5>The obstacle course</h5>
                <ul>
                    <li>Images of illustrated track and actual track</li>
                </ul>
            </div>

        <!-- Visuals Section 1 -->
        <div class="visuals">
            <img src="static/project_2/illustrated_course_2.gif" alt="Looping animation 4" />
            <img src="static/project_2/course_3.gif" alt="Looping animation 4" />
        </div>
        </div>
    </div>
</div>
</section>

<!-- Programming and electronics works Section-->
<section id="cad">
    <div class="container">
        <h2>Design process</h2>
        <p class="mt-3">
            As a group, we researched and evaluated various mechanical energy 
            sources suitable for the project requirements. The source needed 
            to be compact, lightweight, and capable of storing sufficient energy. 
            We calculated the potential energy each mechanism could store and 
            estimated the theoretical energy required for the car to ascend 
            the starting slope and overcome the obstacles along the course.
        </p>

        <h5 style="margin-top: 50px;" > First prototype: Using Spiral Torsion Spring</h5>
        <p class="mt-3">
            Using torsion spring, we had to maximise the number of wheel 
            turns for every unwound distance of the torsion coil. Hence, we
            decided to use gears for tranmission of energy from spring to wheel. 
            Using gears meant we had to optimise the gear ratio which refers to:
            <strong>Gear Ratio</strong> = (Teeth on Driven Gear) ÷ (Teeth on Driver Gear)
        </p>
        <p class="mt-3">
        If a small gear turns a large gear, the larger gear will rotate more slowly,
        but with more torque. The higher the gear ratio, the higher the torque, but speed decreases.
        For example, if gear ratio is 3:1, the output has 3x more torque than input, but 1/3 speed.
        We then had to optimise the gear ratio in accordance to the project requirements.
        </p>

        <!-- Visuals Section 2 -->
        <div class="content-wrapper">
        <div class="visuals">
            <img src="static/project_2/prototype_1.gif" alt="Looping animation 5" />
            <iframe src="static/project_2/prototype_1.html"></iframe>         
        </div>

            <div class="education">
                <h5>Problems faced</h5>
                <ul>
                    <li>
                        We found that the spring was very stiff, causing alot of pressure
                        on the 3D printed parts when wound. The car did not move far 
                        as we were unable to wind the coil. We also found that the car was very heavy, 
                        and wheels were too wide, causing too much friction.
                    </li>
                </ul>
            </div>
        </div>

        <h5 style="margin-top: 20px;" > Next step</h5>
        <p class="mt-3">
            To solve the problems faced, we can use a smaller spring, 
            to allow for easier winding of spring. We can also optimise the 
            design of car to reduce weight. Though we felt the concept had potential,
            due to the long delivery time of a new spring coil, we 
            decided to switch to a mouse trap torsion spring which we had at hand. 
            We took what we learned from the first prototype and implemented it
            to the next prototype.
        </p>

    </div>

    <!-- Second content block: Image 2 & CAD Works -->
    <div class="container">
    <div class="content-wrapper">
        <div class="education">
            <h5> Second Prototype: Using Mouse-trap Torsion Spring</h5>
            <ul>
                <li>We used a cotton string with one end tied to the torsion spring
                    and the other to the gear axle: so when the torsion spring unwinds,
                    it will turn the gears, moving the car forward
                </li>
            </ul>
        </div>

        <div class="visuals">
            <iframe src="static/project_2/prototype_2.html"></iframe>    
            <img src="static/project_2/prototype_2.gif" alt="Looping animation 5" />
        </div>
    </div>

    <h5 style="margin-top: 20px;" > Problems faced and next step</h5>
    <p class="mt-3">
        We found that the car moved slowly due to heavy weight. Also, having 3 gears
        caused there to be alot of friction, causing alot of force from the torsion 
        spring to be ineffieciently transmitted to the rear wheels. Also, the mouse-trap
        torsion spring did not exert enough force to carry 400g load up a 30 degree slope.
        Hence, our next step was to 1) make the car lighter, 2) integrate more torsion springs,
        3) Reduce number of gears while still maintaining optimal gear ratio.
    </p>    

    <!-- Second content block: Image 2 & CAD Works -->
    <div class="content-wrapper">
        <div class="visuals">
            <img src="static/project_2/final_prototype.gif" alt="Looping animation 5" />
            <iframe src="static/project_2/final_prototype.html"></iframe>    
        </div>

        <div class="education">
            <h5> Final Prototype</h5>
            <ul>
                <li>
                    Main improvements include 1) Uses 3 mouse trap torsion spring, 2)
                    Much lighter than previous prototypes due to optimise design, 3) Smoother
                    gear rotation when driving rear wheels.
                </li>
            </ul>
        </div>
    </div>

    <!-- Fourth content block -->
    <div class="container">
        <div class="content-wrapper">
            <div class="education">
                <h5>Exploded view</h5>
                <ul>
                    <li>Made up of 27 parts, secured using m3 screws</li>
                    <li>Parts included laser-cut wood, carbon rods, torsion spring,
                        3D printed gears, wheels and other components
                    </li>
                </ul>
            </div>

            <div class="visuals">
                <div class="image-wrapper">
                    <img src="static/project_2/exploded_view.gif" alt="Slide 2" class="fullscreen-img" />
                    <button class="fullscreen-btn" onclick="openFullscreen(this)">⛶</button>
                </div>        
            </div>
        </div>
    </div>  
    
</div>
</section>

<!-- Testimonial-->
<section id="cad" style="margin-bottom: -10rem;">
    <div class="container">
        <h2>Our Toy-Car put to the test</h2>
        <p class="mt-3">
            After a full semester of working on the car,
             it was time to put the it to the test........
        </p>
        <div class="content-wrapper">
            <div class="visuals_car">
                <img src="static/project_2/final_course.gif" alt="Looping animation 5" />
            </div>
            <div class="education">
                <h5>Success!!</h5>
                <ul>
                    <li>After implementing improvements mentioned above, our car managed to complete 
                        the course!!</li>
                </ul>
            </div>
        </div>
    <h5 style="margin-top: 40px;" >Findings and future improvements</h5>
    <p class="mt-3">
        We found that after a few runs, the torsion spring began to wear on some joints
        due to the pressure it exerts when wounded up. A future improvement would be to 
        reduce the amount of individual parts to ensure the car is more rigid, allowing
        for more optimal force transmission from spring to wheels.
    </p>
    </div>
</div>    
</section>

{% endblock %}

{% block navigation %}
<!-- Navigation Section -->
<section id="navigation-section" class="py-5">
    <div class="container">
        <!-- Back to Top Button (Above the Left and Right Buttons) -->
        <div class="col-4 mb-4">

            <a href="#top" class="btn custom-btn-left back-to-top">
                ↑ Back to Top
            </a>
        </div>


           <!-- Navigation Buttons (Left and Right) -->
           <div class="navigation-buttons d-flex justify-content-between">
            <a href="{{ url_for('views.project_1') }}#top" class="btn custom-btn-left">
                ← Airlab/Blaster
            </a>
            <a href="{{ url_for('views.project_3') }}#top" class="btn custom-btn-right">
                SkyWatchHub →
            </a>
        </div>
    </div>
</section>
{% endblock %}

{% block stl %}
 <!-- Import the custom STL viewer script -->
 {% endblock %}